
# Oracle DB connection params
host: "localhost"
port: 49161
sid: "xe"
username: "system"
password: "oracle"
#encryptedPassword: ""
#encryptionKey: ""

# prefix used to show up metrics in AppDynamics
metricPathPrefix:  "Custom Metrics|ORACLE Server|"